import { NextResponse } from "next/server";
import { getParty } from "@/lib/store";
import { buildRecap } from "@/lib/recap";

export const runtime = "nodejs";

export async function POST(
  req: Request,
  { params }: { params: { code: string } },
) {
  const adminKey = req.headers.get("x-admin-key");
  if (!adminKey) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: { accessToken?: string } = {};
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const accessToken = body.accessToken;
  if (!accessToken) {
    return NextResponse.json({ error: "Missing accessToken" }, { status: 400 });
  }

  const party = await getParty(params.code);
  if (!party) {
    return NextResponse.json({ error: "Party not found" }, { status: 404 });
  }

  const recap = buildRecap(party);
  if (recap.history.length === 0) {
    return NextResponse.json(
      { error: "No songs to export" },
      { status: 400 },
    );
  }

  const videoIds = recap.history.map((h) => h.videoId);
  const deduped = [...new Set(videoIds)];

  try {
    const createRes = await fetch(
      "https://www.googleapis.com/youtube/v3/playlists?part=snippet,status",
      {
        method: "POST",
        headers: {
          authorization: `Bearer ${accessToken}`,
          "content-type": "application/json",
        },
        body: JSON.stringify({
          snippet: {
            title: `VideoJam — ${party.name || params.code}`,
            description: `Songs played at the VideoJam party "${party.name || params.code}" (code ${params.code}). ${deduped.length} tracks. Generated by videojam.net`,
          },
          status: { privacyStatus: "unlisted" },
        }),
      },
    );

    if (!createRes.ok) {
      const err = await createRes.text().catch(() => "");
      console.error("[export-playlist] create failed", createRes.status, err);
      return NextResponse.json(
        { error: "Failed to create YouTube playlist" },
        { status: 502 },
      );
    }

    const playlist = (await createRes.json()) as {
      id: string;
      snippet: { title: string };
    };
    const playlistId = playlist.id;

    let added = 0;
    for (const videoId of deduped) {
      const itemRes = await fetch(
        "https://www.googleapis.com/youtube/v3/playlistItems?part=snippet",
        {
          method: "POST",
          headers: {
            authorization: `Bearer ${accessToken}`,
            "content-type": "application/json",
          },
          body: JSON.stringify({
            snippet: {
              playlistId,
              resourceId: { kind: "youtube#video", videoId },
            },
          }),
        },
      );
      if (itemRes.ok) {
        added++;
      } else {
        console.warn(
          `[export-playlist] failed to add ${videoId}:`,
          itemRes.status,
        );
      }
    }

    const playlistUrl = `https://www.youtube.com/playlist?list=${playlistId}`;

    return NextResponse.json({
      ok: true,
      playlistId,
      playlistUrl,
      total: deduped.length,
      added,
    });
  } catch (err) {
    console.error("[export-playlist] threw", err);
    return NextResponse.json(
      { error: "Network error creating playlist" },
      { status: 502 },
    );
  }
}
